### ISSUE TITLE
你好我有一个安装问题

### ISSUE THREAD

**Issue by a375891918** [Wanghaoran86/WangPlugin#1]
我是使用的6.27的测试版本，在解除阻止之后放入PKHEX的exe同文件夹和Plugins文件夹好像都没能安装成功，想请问一下该如何安装呢，因为在项目主页没有看到安装和使用的教程，非常不好意思打扰，谢谢

**Comment by 8CBCA403** [comment]
去Release寻找pre-release
当前适配PKHeX版本:PKHeX Development Build 22.6.27-movesource.1+73
https://projectpokemon.org/home/files/file/2445-pkhex-development-build/
去此链接下载PKHeX Development Build 22.6.27-movesource.1+73此版本

**Comment by 8CBCA403** [comment]
[PKHeX-framework.zip](https://github.com/Wanghaoran86/WangPlugin/files/9155349/PKHeX-framework.zip)
尝试使用此版本
